application: code-highlighter
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: index.html

- url: /html
  static_dir: html
  expiration: "1d"
  
- url: /js
  static_dir: js
  expiration: "7d"